version: '3.0'
services:
  web:
    image: roryjf/capcodigitalengineeringcourse
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      - DB_HOST_NAME=db
  db:
    image: mongo
    ports:
      - "27017:27017"
