apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kub.yml
      kompose.version: 1.18.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: db
    name: db
  spec:
    ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
    selector:
      io.kompose.service: db
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kub.yml
      kompose.version: 1.18.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: elk
    name: elk
  spec:
    ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "5044"
      port: 5044
      targetPort: 5044
    selector:
      io.kompose.service: elk
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kub.yml
      kompose.version: 1.18.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: web
    name: web
  spec:
    ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
    selector:
      io.kompose.service: web
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kub.yml
      kompose.version: 1.18.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: zookeeper
    name: zookeeper
  spec:
    ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
    selector:
      io.kompose.service: zookeeper
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kub.yml
      kompose.version: 1.18.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: db
    name: db
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: db
      spec:
        containers:
        - image: mongo
          name: db
          ports:
          - containerPort: 27017
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kub.yml
      kompose.version: 1.18.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: elk
    name: elk
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: elk
      spec:
        containers:
        - image: sebp/elk
          name: elk
          ports:
          - containerPort: 5601
          - containerPort: 9200
          - containerPort: 5044
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kub.yml
      kompose.version: 1.18.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: web
    name: web
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: web
      spec:
        containers:
        - env:
          - name: DB_HOST_NAME
            value: db
          image: roryjf/capcodigitalengineeringcourse
          name: web
          ports:
          - containerPort: 8090
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o kub.yml
      kompose.version: 1.18.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: zookeeper
    name: zookeeper
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: zookeeper
      spec:
        containers:
        - image: wurstmeister/zookeeper
          name: zookeeper
          ports:
          - containerPort: 2181
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

