apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: DB_HOST_NAME
          value: db
        image: roryjf/capcodigitalengineeringcourse
        name: web
        ports:
        - containerPort: 8090
        resources: {}
      restartPolicy: Always
status: {}
